version: '3.7'

services:
    bot:
        image: squirrelnet/nebula8
        build:
            context: docker/bot/
        volumes:
            - bot_data:/opt/service/data
            - bot_requirements:/root
        environment:
            REPO: $REPO
            BRANCH: $BRANCH

            HOST: $HOST
            PORT: $PORT
            USER: $USER
            PASSWORD: $PASSWORD
            DBNAME: $DBNAME

            BOT_TOKEN: $BOT_TOKEN
            SUPERADMIN: $SUPERADMIN
            OWNER: $OWNER
            DEFAULT_WELCOME:  $DEFAULT_WELCOME
            DEFAULT_RULES:  $DEFAULT_RULES
            DEFAULT_LOG_CHANNEL:  $DEFAULT_LOG_CHANNEL
            DEFAULT_STAFF_GROUP:  $DEFAULT_STAFF_GROUP

            OPENWEATHER_API: $OPENWEATHER_API
            ENABLE_PLUGINS: $ENABLE_PLUGINS
            DEFAULT_LANGUAGE: $DEFAULT_LANGUAGE
            VERSION: $VERSION
            VERSION_NAME: $VERSION_NAME

            DEBUG: $DEBUG

volumes:
    bot_data:
    bot_requirements: